### ISSUE TITLE
Building with Carthage not supported

### ISSUE THREAD

**Issue by greimers** [tent/hawk-objc#6]
hawk-objc cannot be build with [Carthage dependency manager](https://github.com/Carthage/Carthage). Carthage will fail with:

    Dependency "hawk-objc" has no shared framework schemes

The [schemes must be shared](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework) for Carthage to build the project.

**Comment by jvatic** [comment]
Feel free to submit a PR to resolve this.

**Comment by jvatic** [comment]
#7 should address this
